# Generated by Django 5.0.3 on 2024-03-10 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventsapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='description',
            new_name='event_description',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='fullname',
            new_name='event_name',
        ),
    ]
