# Generated by Django 5.0.3 on 2024-03-10 19:08

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventsapp', '0005_remove_event_attendee_event_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='created_by',
            field=models.CharField(default=uuid.uuid4, max_length=36),
        ),
    ]
